Repository puppetlabs/puppetlabs-facter_task, pull requests merged in 2019-11, with the labels that each got.

#91 pdksync - (FM-8634) ensure encrypted communication for fixtures
  .fixtures.yml
Labels: maintenance

#93 pdksync - FM-8499 - remove ubuntu14 support
  metadata.json
  provision.yaml
Labels: backwards-incompatible

#94 MODULES-10096 - Release version v0.6.0
  CHANGELOG.md
  metadata.json
Labels: maintenance

#98 pdksync - remove deploy to forge from travis
  .sync.yml
  .travis.yml
  Gemfile
  metadata.json
Labels: maintenance

#96 (MAINT) remove deploy to forge execution from travis
  .travis.yml
Labels: maintenance

#97 (FM-8688) - Addition of support for CentOS 8
  metadata.json
  provision.yaml
Labels: feature

#100 (MODULES-10120) enable simplecov; update to PDK 1.14.1; minor cleanups
  .gitignore
  .pdkignore
  .project
  .sync.yml
  .travis.yml
  appveyor.yml
  metadata.json
Labels: maintenance
